FROM amazonlinux:2.0.20220805.0

LABEL maintainer="jeff@cloudreactor.io"

RUN yum install -y shadow-utils openssl binutils glibc ca-certificates curl python3.7 python3-pip libssl-dev

RUN groupadd appuser && useradd -g appuser --create-home appuser
USER appuser
WORKDIR /home/appuser

#RUN curl -O https://bootstrap.pypa.io/get-pip.py
#RUN python3 get-pip.py --user

RUN pip3 install --no-input --no-cache-dir --upgrade pip==22.2.2

COPY proc_wrapper-requirements.txt .

RUN pip3 install -r proc_wrapper-requirements.txt
RUN pip3 install certifi
RUN pip3 install pyinstaller==5.4.1

COPY proc_wrapper ./proc_wrapper

RUN python3 /home/appuser/.local/lib/python3.7/site-packages/PyInstaller/ -F --name proc_wrapper --noupx --clean proc_wrapper/__main__.py

ENTRYPOINT ["ls", "-la", "dist/proc_wrapper"]
