# Run pre-commit autoupdate and create a pull request
name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          # CI won't be running on pull requests if using GITHUB_TOKEN
          # We instead use a personal access token (PAT) with the 'repo' scope
          # https://github.com/settings/tokens/new?scopes=repo
          token: ${{ secrets.GH_PAT }}
          branch: update/pre-commit-autoupdate
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update of pre-commit hooks to latest versions.
          labels: dependencies
